# # Taken and modified from Coste's(tlc4418) accelerate_config.yaml

compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: configs/deepspeed_rl.json
  zero3_init_flag: false
distributed_type: DEEPSPEED
main_process_port: 12500
downcast_bf16: no
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
